[themes]
  [themes.light]
  primary = "#ffffff"
  secondary = "#f9f9f9"
  tertiary = "#e0e0e0"
  text = "#212529"
  button = "#007bff"
  button_text = "#ffffff"
  border = "#ced4da"

  [themes.dark]
  primary = "#212529"
  secondary = "#343a40"
  tertiary = "#495057"
  text = "#f8f9fa"
  button = "#007bff"
  button_text = "#ffffff"
  border = "#6c757d"
